apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
spec:
  containers:
    - name: bad-container
      image: nginx
      securityContext:
        privileged: true         # ❌ Privileged -> policy бузат
      resources: {}              # ❌ Resource limits жок
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath:                 # ❌ HostPath -> policy бузат
        path: /tmp
